---
title: "git_01"
author: "Michael Harte"
date: "2/23/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

Five little girls, of Five, Four, Three, Two, One:   
Rolling on the hearthrug, full of tricks and fun.   

Five rosy girls, in years from Ten to Six:  
Sitting down to lessons - no more time for tricks.   

Five growing girls, from Fifteen to Eleven:  
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

It was many and many a year ago,   
   In a kingdom by the sea,    
That a maiden there lived whom you may know   
   By the name of ANNABEL LEE;--    
And this maiden she lived with no other thought   
   Than to love and be loved by me. 
She was a child and I was a child,   
   In this kingdom by the sea,   
But we loved with a love that was more than love--   
   I and my Annabel Lee--   
With a love that the winged seraphs of heaven   
   Coveted her and me.   

And this was the reason that, long ago,   
   In this kingdom by the sea,    
A wind blew out of a cloud by night   
   Chilling my Annabel Lee;   
So that her high-born kinsman came   
   And bore her away from me,   
To shut her up in a sepulchre   
   In this kingdom by the sea.   
<!--Put a short poem of your choice 8-20 lines,here!-->
